# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

loom_version=1.18.2

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.2
minecraft_label=26.2
loader_version=0.19.5
java_version=25

# Mod Properties
mod_version = 1.2.2
maven_group = com.quarrymod
archives_base_name = quarry-reborn

# Dependencies
fabric_version=0.152.1+26.2
# Can be found on https://github.com/TechReborn/TechReborn/releases
tr_version=26.2:6.1.1
rc_version=26.2:6.1.1
