# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

loom_version=1.13.6

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.10
minecraft_label=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.17.3
java_version=21

# Mod Properties
mod_version = 1.2.2
maven_group = com.quarrymod
archives_base_name = quarry-reborn

# Dependencies
fabric_version=0.138.4+1.21.10
# Can be found on https://github.com/TechReborn/TechReborn/releases
tr_version=1.21.10:5.15.0
rc_version=1.21.10:5.15.0
